### ISSUE TITLE
The required field feature doesn't work for the predefined category field.

### ISSUE THREAD

**Issue by prottoy210385** [weDevsOfficial/wp-user-frontend#1321] opened 2022-12-10 01:52 UTC
Description: The required field feature doesn't work for the predefined category field. Here is the video link to this issue: https://www.loom.com/share/720895647b0b49d2a2839dbebc29b0a1

**System Status-**

WordPress version: 6.1.1
WPUF Lite version: 3.5.28
WPUF Pro version: 3.4.11

**Comment by anik-fahmid** [comment] 2023-01-06 10:11
duplicate of : [Required field doesn't work for the predefined category field in Post form#496](https://github.com/weDevsOfficial/wpuf-pro/issues/496)

**Closed** 2023-01-06 10:12 UTC
