### ISSUE TITLE
The billing address is not displaying on the payment page for guest users during check-out of the WPUF subscription

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1077] opened 2021-03-12 16:59 UTC
**Description:**

The billing address is not displaying on the payment page for guest users during check-out of the WPUF subscription.
Payment page for the logged-in user - http://prntscr.com/10h98s1
Payment page for logged-out(guest) user - http://prntscr.com/10jt8sk

**How to reproduce:**
1. Make sure you have the Billing Address enabled from the customizing > WP User Frontend area- 
2. Then try to purchase the WPUF subscription package; you will see for the logged-in user, you can input billing address info, but it won't be visible for a guest user on the payment page.

**Expected behaviour:**
It should display the billing info for the non-logged in users also as like the WooCommerce check-out page.

**Site info:**
WordPress Version - 5.7
PHP Version	- 7.4.13
Active theme - Astra (3.1.2)
WooCommerce	Version - 5.1.0 
WP User Frontend Version - 3.5.14 by weDevs

**Comment by Anticosti** [comment] 2021-03-12 17:56
Nice catch. The "as like the WooCommerce check-out page" is the key here.

**Comment by shabnam611** [comment] 2021-03-13 12:59
@zamandevs please check this as soon as possible.

**Comment by Anticosti** [comment] 2021-03-19 21:43
Just upgraded:
WP User Frontend - Version 3.5.15
WP User Frontend Pro - Version 3.4.6
This is still not solved.
See short video:
[Video](https://www.loom.com/share/df8acbfe6b6c474bb2ff2f392f64d60e)

**Comment by Anticosti** [comment] 2021-04-10 02:36
Any ETA?

**Comment by zamandevs** [comment] 2021-04-12 03:01
@Anticosti Will be on the next release.

**Comment by Anticosti** [comment] 2021-04-12 03:03
Thank you so much Zamandevs. Much appreciated. Sincerly.

**Comment by MimiDev** [comment] 2021-04-18 04:07
As the person who lodged this issue with WeDevs support, is someone able to confirm whether this issue is also related to [forced] Subscription packs not being applied to new users during registration please?  ...or is that a separate issue?
Thank you

**Comment by Anticosti** [comment] 2021-04-19 19:43
Is it possible that this issue would be due to a typo in the code like this one ?:
https://www.dropbox.com/s/jvn5vnv3l6qe5hj/biiling.png?dl=0

**Comment by MimiDev** [comment] 2021-04-20 02:57
> Is it possible that this issue would be due to a typo in the code like this one ?:
> https://www.dropbox.com/s/jvn5vnv3l6qe5hj/biiling.png?dl=0

Interesting. I'd love to test this ASAP. Can you tell me which file I'd find the relevant code please?

**Comment by Anticosti** [comment] 2021-04-20 03:17
> Interesting. I'd love to test this ASAP. Can you tell me which file I'd find the relevant code please?

I'm not sure which file to look at? Altough, if you go to the "Account" page and click on the "Billing Address" tab... Check the source code; you will see that "biiling" is widely used. I suspect this is also the case at checkout.

**Comment by MimiDev** [comment] 2021-04-20 04:09
> > Interesting. I'd love to test this ASAP. Can you tell me which file I'd find the relevant code please?
> 
> I'm not sure which file to look at? Altough, if you go to the "Account" page and click on the "Billing Address" tab... Check the source code; you will see that "biiling" is widely used. I suspect this is also the case at checkout.

Thank you, yes. I found the 'Billing-address.js' file and there are *lots* of references to 'biiling_address' (with spelling mistake, so that seems to be used throughout.

Will leave it to the developers to sort out I guess.

**Comment by Anticosti** [comment] 2021-05-23 18:43
**OK. I am always trying to be nice and give a chance but now... My patience has it's limits.
This vital and important issue is more than a month old.
This is not resolved yet. C'mon WeDevs Team!
Let Dorka aside a bit and let's concentrate on WP User Frontend Pro - business**

**Comment by zamandevs** [comment] 2021-05-23 18:48
@Anticosti We are really sorry for the inconvenience. solved all of these related issues months ago. but unfortunately, we couldn't release it. will release immediately. again really sorry for the inconvenience & request you to be patient for couple of days.

**Comment by MimiDev** [comment] 2021-05-24 03:36
I simply can't believe what I'm reading!!!  I have been writing to support regarding this issue for about 2 MONTHS!!  Such a basic part of functionality should have been attended to ASAP. Do support staff honestly not communicate with developers??

**Comment by MimiDev** [comment] 2021-05-24 03:39
And in case developers aren't aware - I did find that the Billing Address is displaying for guest user - during the Registration process - but the actual billing address isn't saved with the persons new account (when viewed in the Dashboard/Account page).

It seems that someone needs to go through and THOROUGHLY check these processes in WPUF. ....PLEASE!!

**Comment by zamandevs** [comment] 2021-05-24 03:41
@MimiDev Honestly Our support is the best in the world. they always communicate with devs. some of our devs were in long leave. we solved all of the related issues months ago but couldn't release them. will release immediately. request you to wait for a couple of days.

**Comment by MimiDev** [comment] 2021-05-24 04:27
> @MimiDev Honestly Our support is the best in the world. they always communicate with devs. some of our devs were in long leave. we solved all of the related issues months ago but couldn't release them. will release immediately. request you to wait for a couple of days.

Thank you for the prompt response. Much appreciated.
I've been having a very frustrating time with this and support staff have always been wonderful, but something seems to get lost in communication. 
I'll look forward to the update. 
Thanks again

**Comment by Anticosti** [comment] 2021-05-26 13:14
@zamandevs 
"will release immediately. again really sorry for the inconvenience & request you to be patient for couple of days."
I have important business to do. Success is base on this fix, ASAP.
Thank you for your understanding.

**Comment by zamandevs** [comment] 2021-05-27 02:40
@Anticosti Please provide your email on our support(Tell them to provide me) or here. i am mailing you related PR which is in a private repo. I think this is the ASAP way.

**Comment by Anticosti** [comment] 2021-05-27 02:58
@zamandevs Thank you for this quick reply.
Here's my email:



admin(at)iroutier.com

**Comment by MimiDev** [comment] 2021-05-27 12:54
> @MimiDev Honestly Our support is the best in the world. they always communicate with devs. some of our devs were in long leave. we solved all of the related issues months ago but couldn't release them. will release immediately. request you to wait for a couple of days.

Can you give an idea of when the update will be released please? @zamandevs

**Comment by zamandevs** [comment] 2021-05-27 13:11
@MimiDev We will release within next monday. in this time if you want please create a ticket on our support and mention me.i will help you immediately.

**Comment by MimiDev** [comment] 2021-05-28 10:42
Lovely. Thank you @zamandevs  ...Monday will be fine :)

**Comment by Anticosti** [comment] 2021-05-28 14:40
I'll beleive it when I see it - working

**Comment by Anticosti** [comment] 2021-05-29 13:33
@MimiDev 
Are you using - like me - a custom Pricing Table plugin?

**Comment by MimiDev** [comment] 2021-05-30 10:46
> @MimiDev
> Are you using - like me - a custom Pricing Table plugin?

No I'm not, unfrotunately @Anticosti

**Comment by Anticosti** [comment] 2021-05-31 20:07
We are Monday here (16:00 EDT) and there is 8 hours in the day

**Comment by MimiDev** [comment] 2021-06-01 04:41
I wish to share @Anticosti sentiments. I feel bad that it seems like we're 'ganging up on you' @zamandevs but it is now Tuesday where I am and there is no update apparent.
I hope you can understand how baffling this is, considering that you wrote previously that "these issues were fixed months ago"! If that is in fact the case, there really shouldn't be any cause for a delay. As such, this tells us that there *is* in fact a problem and no, this isn't yet fixed.
Can you please be honest with is. There is clearly a problem here and, after months of waiting, I think we deserve some transparency. ...is there maybe any way we can help?
I have a client who is waiting for me to get a website into final testing, which is already well overdue, and I'm hesitant to do so with less than ideal functionality. Surely you can understand this puts us in a very difficult situation. As I do small amounts of programming, I understand that there could be an awkward issue facing you at the moment. ..but maybe not?
Personally, I need to know if this functionality is in fact rectified and if not, if there is a problem that is going to cause significant continued delay. If so, I need to make changes to the website I am developing for my client. 
We'll look forward to your response. 
Thank you.

**Comment by zamandevs** [comment] 2021-06-01 04:47
@MimiDev Honesty is what stayed us on the path. This issue solved months ago it's true but we have other PR which produce some unexpected behavior. working hard to solve this ASAP. when these issues will solve will release immediately. bad time i reckon. Thanks for your patience & support.

**Comment by MimiDev** [comment] 2021-06-01 04:50
I do appreciate your response. Thank you. Are you at all able to provide an idea of timeline do you think?

**Comment by zamandevs** [comment] 2021-06-01 04:52
@MimiDev Within Friday. Thanks for your support.

**Comment by MimiDev** [comment] 2021-06-08 03:53
> @MimiDev Within Friday. Thanks for your support.

Hi @zamandevs  ...as I don't see the update for the plugin in the WP Admin, could be have a bit of a progress update please? For something that was "fixed months ago", it's a little baffling that this update is not forthcoming.
Thank you.

**Comment by Anticosti** [comment] 2021-06-08 10:52
Meanwhile... weDevs still run  - every two weeks - their famous "45% Off" deal. The question is: is WPUF Pro really worth the full price? If you are going to sell subscriptions... this is too buggy. It does not even complies with compound taxes as WooCommerce does. This is not serious.

**Comment by MimiDev** [comment] 2021-06-14 01:20
The eventual release of the update is much appreciated, thank you @zamandevs  ...I am already finding some bugs however. Has this functionality been thoroughly been tested?
With further bug reports, would you like me to post them here or shall I go through the normal support channels?

**Comment by zamandevs** [comment] 2021-06-14 03:47
Dear @Anticosti your effort is much appreciated. you can help us in this regard by requesting missing piceces on subscription or another part of the plugin. this plugin has many features which make it valuable. we are working on this to make it better.

@MimiDev Thanks for your support and effort. if you come through normal support channel it will better for us. also if you want to report here you can with the full scenario.

**Comment by MimiDev** [comment] 2021-06-20 03:13
Hi @zamandevs  ...I am a little baffled. I've been testing my site since the update and honestly, nothing at all appears to have changed!  The Billing Address is not being saved when a new subscription is paid for.

I am also getting the display of a Country (Afghanistan!) in the receipt PDF that is sent via email when a payment is approved - and this is with the Country field HIDDEN in the Customiser settings for Billing Address.

 Is there something I'm missing here??

**Comment by Anticosti** [comment] 2021-06-20 13:40
I would add that with every weDevs updates... comes bad surprises. Just like if they don't care about us users. They DO care a lot about money. I am getting more and more sick of this Bollywood scheme.

**Comment by Anticosti** [comment] 2021-06-20 13:45
Instead of weDevs, why not call yourselves weBreak ?

**Comment by zamandevs** [comment] 2021-06-21 03:24
@MimiDev What you stated above shouldn't happen. if you face anything wrong, please give your site details through support ticket. we will take care. 

@Anticosti please be specific about what you've got wrong. besides if you've face anything wrong give your issue & site details through the support channel.

**Closed by zamandevs** 2021-06-21 03:24 UTC
Labels: bug
