### ISSUE TITLE
WPUF x Dokan Subscription x Stripe Bug

### ISSUE THREAD

**Issue by elphcheck242** [weDevsOfficial/wp-user-frontend#1404] opened 2024-01-03 20:19 UTC
Hello, I was asked to make a new support ticket here - this issue is ongoing for most of this year. 
Previous support thread is: #835872 & #841498 (on old Dokan Support) 

We use WPUF to create a custom registration form, instead of using the default Dokan Registration form. We mostly use this so we can get the new vendors to upload their avatar and shop banner on the initial registration form. It helps with faster on-boarding. 

**Issue:**
All new vendors that sign up and go firstly to purchase our paid Dokan subscription tiers are affected. They get charged for the Dokan subscription, but Stripe & Dokan Subscription don't connect correctly, so the vendors cannot use their vendor account. They had to switch to a ''free" subscription, and their account correctly registers, but were still being charged for the paid subscription. Which we have to manually cancel each time.  

**How to Reproduce The Bug:**
When registering a vendor account, and then purchasing a paid subscription, occasionally the paid subscription doesn't register with dokan. The vendor cannot use their account as dokan thinks they haven't chosen a subscription (so not fully registered). In stripe the subscription payment goes through and they get monthly charges. After this if the vendor registers to the Free subscription, still in stripe they get the monthly paid subscription charge. This has happened a lot of times now. 

We've tried rolling back which worked, but then you fixed the AJAX issue, however the issue is still continuing somehow for some new vendors. It's not a caching issue, and it's not a plugin conflict. 

Open to your investigation. 

--

**_WEDEVS SUPPORT: Tanvir Hasan:**

I'm sorry to hear that you're experiencing issues with the Dokan Dashboard and the registration form. I understand the frustration this can cause and I'm here to assist you. From your description, it seems that the issue is related to the WP User Frontend (WPUF) plugin, which is required for Dokan to function properly. Since you've rolled back WPUF to an earlier version to resolve the Ajax issue, it's important to note that fixing this issue would likely involve adjustments on the WPUF side.

I recommend reaching out to the WP User Frontend development team regarding the specific issue you're encountering. To do this, you can create an issue on the WP User Frontend GitHub public repository. You can open a new issue at the following link: https://github.com/weDevsOfficial/wp-user-frontend/issues/new. This way, the issue can gain attention from the developers, who can then work on implementing a solution.

I hope this approach will lead to a resolution for the problem you're facing. If there's anything else I can assist you with or if you have further questions, please don't hesitate to reach out._

**Comment by sapayth** [comment] 2024-01-08 06:32
Hello @elphcheck242,

Sorry to hear about your problem. Can you please make a video about the problem so that we can reproduce the issue and check it in every possible way.

**Comment by elphcheck242** [comment] 2024-01-08 14:19
I can't as it doesn't affect everyone. I have a lot of details listed in
the support tickets I mentioned, do you have access to them?

**Comment by sapayth** [comment] 2024-01-09 05:30
Sadly I don't have access to the support tickets. It's ok if the issue is not arising, you can make a video anyway. That way we can see the steps you are following and we might do the same to recreate the scenario

**Comment by sapayth** [comment] 2024-01-11 07:02
Hello @elphcheck242,

I believe you are managing your subscriptions through Dokan. If your payments are done through Dokan, maybe there are some recurring payment activated. If you want to manage multiple subscriptions and want to show them in user profile, you can try [WPUF subscription](https://wedevs.com/docs/wp-user-frontend-pro/subscription-payment/).

Also if you share your end goal, what exactly you want, we might guide you through the setup process.

Feel free to notify us of any queries.

**Comment by Rat01047** [comment] 2024-05-03 05:15
@anik-fahmid,
@sapayth has given a solution regarding this topic.
Closing this issue now.

**Closed by Rat01047** 2024-05-03 05:15 UTC
Labels: needs: testing
