### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by DanielOizumi** [weDevsOfficial/wp-user-frontend#762] opened 2020-01-14 12:45 UTC
Hi,

Since the last update I am receiving these php warning messages on the backend (wp-admin) and it  is causing some issues when updating some settings.

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/wp-user-frontend/includes/free/edit-user.php:201) in wp-includes/functions.php on line 6029

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/wp-user-frontend/includes/free/edit-user.php:201) in wp-admin/includes/misc.php on line 1252

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/wp-user-frontend/includes/free/edit-user.php:201) in wp-includes/pluggable.php on line 1265

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/wp-user-frontend/includes/free/edit-user.php:201) in wp-includes/pluggable.php on line 1268

**Comment by miroconsultant** [comment] 2020-01-15 11:41
Same problem here: https://club.hired.ro

**Comment by miroconsultant** [comment] 2020-01-15 11:59
Reversed to previous version (3.1.14) until the problem is solved.

**Comment by tjahonen** [comment] 2020-01-16 08:32
The error can be fixed by removing all empty characters between php tags on 
wp-user-frontend/includes/free/edit-user.php lines 200 & 202

**Comment by Web4Guru** [comment] 2020-01-16 21:33
I updated plugins yesterday and realized I had the same issue today.  I can confirm that tjajonen's fix above works.

> The error can be fixed by removing all empty characters between php tags on
> wp-user-frontend/includes/free/edit-user.php lines 200 & 202

**Comment by ediamin** [comment] 2020-01-29 10:07
fixes via 330dd18dd9d0161d8680d274855efda12f01486e

**Closed by ediamin** 2020-01-29 10:07 UTC
