### ISSUE TITLE
Adding url in Terms and Condtion Submission content will wipe out your form

### ISSUE THREAD

**Issue by Imageburst** [weDevsOfficial/wp-user-frontend#804] opened 2020-02-05 04:03 UTC
When I recently tried to add the "Terms & Conditions" and try to edit and add either the absolute or relative url to where my terms and privacy policy page exist, then hit save, it completely clears the entire form. This is a major bug, users of this form, please be aware that this will remove all existing fields and there's no way to get them back. So make sure you test stuff on a dummy or pre-existing template.

**Comment by itowhid06** [comment] 2020-02-05 04:12
Hello @Imageburst, What version of WP User Frontend are you using? This issue with "Terms & Conditions" field has been fixed in https://github.com/weDevsOfficial/wp-user-frontend/commit/61a7961352765cfc5b542e9770a73ffa784bf1bf and released in WP User Frontend v3.1.17. Can you please test it with latest version and see if the issue is still persisting?
Thank you.

**Comment by Imageburst** [comment] 2020-02-10 04:08
You are right, after updating to the latest version, this has been resolved, Please mark this as resolved and close it out. 

Thank You!

**Closed** 2020-02-10 04:13 UTC
Labels: resolved
