### ISSUE TITLE
New Post Notification is send as plain text, not HTML

### ISSUE THREAD

**Issue by errotu** [weDevsOfficial/wp-user-frontend#1249] opened 2022-03-05 08:01 UTC
Once again, thank you for your great plugin!

When a guest submits a new post, I'd like to get notified by e-mail. Therefore, I set up a "New Post Notification". As some of the mail's content is HTML (for example, the post content but also the post edit link), it would make sense to send the notification as HTML. Currently, it is send as plain text, making all the HTML tags visibly (which decreases readibility). I guess it could be fixed if the the content-type were set to HTML (unfortunately, I'm not sure where to do this):

> Content-Type: text/html

// Edit: Bugfix submitted as PR https://github.com/errotu/wp-user-frontend/commit/1817b04e3f48fc66a6a4bda62107fe5096f9a435

**Comment by sapayth** [comment] 2022-03-18 03:19
Hello @errotu,
Thanks for your valuable contribution. The problem is fixed in the new release. Please update your plugin and give it a go.

**Closed** 2022-04-13 03:19 UTC
