### ISSUE TITLE
Taxonomies Not Saving

### ISSUE THREAD

**Issue by Tetto319** [weDevsOfficial/wp-user-frontend#821] opened 2020-02-26 05:40 UTC
Hello,

I have searched far and wide, got some links of people raising this same issue but in none of it did I see a working response.

I have some custom taxonomies attached to the default WP post type. Here is my issue: Everytime I a post is submitted via the front end, none of the taxonomies that I select get saved. It requires that I go to the back end and select those taxonomies again for them to be saved successfully.

Please, HELP! This is an amazing plugin, the best in its category. I want to keep using it.

**Comment by Anticosti** [comment] 2020-02-26 15:18
I had the same issue and the Support Team (MM Aurangajeb) quickly provided me with this solution:
Download these two files:
https://drive.google.com/drive/folders/1u7wNUdzgc3LZZvVEas-LiiaIogY6PrMx?usp=sharing
and place these in there:
wp-content/plugins/wp-user-frontend/wpuf-functions.php (was missing)
wp-content/plugins/wp-user-frontend/includes/class-frontend-form-post.php (replace)

**Comment by Tetto319** [comment] 2020-02-26 19:26
Thanks for your reply.

Unfortunately it seems not to work on my site. The functions file was actually there and the second one was empty. I however did replace both, but they do not seem to have changed anything.

Anything else to try?

**Comment by Anticosti** [comment] 2020-02-26 19:28
Have you clear all the cache?

**Comment by Tetto319** [comment] 2020-02-26 19:34
Yes, just did...Litespeed and browser. Tried it, still nothing.

**Comment by Anticosti** [comment] 2020-02-26 20:03
This could sound as s plugin conflict.
I will have to try on a fresh install...
Which version numbers are you using?

**Comment by Anticosti** [comment] 2020-02-26 22:54
Did some testing on a fresh install.
I confirm your issue.

Using:
WP User Frontend Version 3.1.17
WP User Frontend Pro - business Version 3.1.13

01. I created a basic Post Form;
02. I created a Custom Taxonomy (**Colors**) with Pods;
03. I added this new Taxonomy to my Post Form;
04. On Frontend form, no Taxonomy is showing. Just the label **Colors**
When I check in the source, this is what I see:
`<li class="wpuf-el color field-size-large has-error" data-label="color">

                <div class="wpuf-label">
            <label for="color_34">color <span class="required">*</span></label>
        </div>
                    <div class="wpuf-fields wpuf_color_checkbox_47_34" data-required="yes" data-type="tax-checkbox">
        <ul class="wpuf-category-checklist"><input type="hidden" name="color" value="0"></ul>        <span class="wpuf-wordlimit-message wpuf-help"></span>
        
        </div><div class="wpuf-error-msg">color is required</div></li>`

**Comment by itowhid06** [comment] 2020-02-27 02:58
Hello @Anticosti , Did you associated the custom taxonomy with post?

In my testing, I was unable to reproduce the issue. It displays all the taxonomy terms as usual.

If you are still facing the issue, please open a ticket [Here](http://wedevs.com/contact).

**Comment by Tetto319** [comment] 2020-02-27 03:04
I want to try all else...including a fresh install, checking for possible conflicts and all to see if anything works.

**Comment by Tetto319** [comment] 2020-02-27 03:10
I am using CPTUI for custom taxonomies, and the post type is the default WP post. The only functionality that is suffering because of this is the search which I have Search and FIlter Pro for.

**Comment by Anticosti** [comment] 2020-02-27 03:24
I have been able to make my Colors terms to show frontend. I can pick any combination. Altough as @Tetto319 said, they are not saved on Submit.

**Comment by Anticosti** [comment] 2020-02-27 03:53
@itowhid06 
To answer your question: "Did you associated the custom taxonomy with post?"
Yes. I associated my custom taxonomy with Posts.

Thanks

**Comment by Anticosti** [comment] 2020-02-27 04:09
@itowhid06 @Tetto319 
Curiously, when trying **on my main current project** (many (55) plugins activated), I am not encountering this issue. **I have no problems**. I have the feeling that it could simply (not sure?) be the patches I applied today from other issues. Hard to say. Or it could just be a configuration (there is so many in WPUF) that needs to be activated or desactivated....?

Regards

**Comment by Anticosti** [comment] 2020-02-27 04:31
@Tetto319
I need to understand carefully what you want to acheive.
01. You want Subscribers to be able to post Articles (Posts) to your site?
02. Do they have to buy a Subscription?

Thanks

**Comment by Tetto319** [comment] 2020-02-27 05:28
@Anticosti 
1. Yes
2. No but they have to be logged in to post.

**Comment by Tetto319** [comment] 2020-02-27 06:18
@Anticosti @itowhid06 

It worked! The issue was actually not caused by WPUF. There are 4 plugins being used for this: ACF, CPTUI, WPUF and S&F. S&F was not picking the data posted through WPUF because of a wrong setting in it and in ACF. In other words, no bug on any of them; just a settings issue.

I appreciate the time you took to respond. I will definitely buy the business version.

**Comment by itowhid06** [comment] 2020-02-27 06:50
Closing the issue based on last reply. Thank you to both of you.

**Closed by itowhid06** 2020-02-27 06:50 UTC
