### ISSUE TITLE
Word count min limit not working

### ISSUE THREAD

**Issue by ijdk-loop** [weDevsOfficial/wp-user-frontend#1225] opened 2022-01-07 15:14 UTC
The min word count is made 600. But i see that less than 600 word count can be sent for "pending review". 
please use uid: ijdk7777  and pass: asdfg@123456789012
site https://www.innertowords.com/wp-login.php

**Comment by sapayth** [comment] 2022-01-10 02:54
Hello @ijdk-loop,
I think new posts are sending for "pending review" for the form settings. Please have a look at [this doc](https://wedevs.com/docs/wp-user-frontend-pro/posting-forms/display-form-settings/) to find the form settings. Please check if it is selected "Pending Review" from the form settings > Post settings > Post Status. Hope this will solve your problem.

**Comment by ijdk-loop** [comment] 2022-01-10 08:24
sorry, perhaps I could not clearly state the problem.
My problem is "The min word count is made 600. But i see that **less than** 600 word count can be sent"

**Comment by sapayth** [comment] 2022-01-11 03:13
Hello @ijdk-loop,
Sorry for the inconvenience. Please try the solution below.

In `wp-user-frontend > includes > class-frontend-form-post` line no `311` add the below code:

```
foreach ( $this->form_fields as $single_field ) {
    if ( empty( $single_field['content_restriction'] ) ) {
        continue;
    }
    $restricted_num = $single_field['content_restriction'];
    $restriction_to = ! empty( $single_field['restriction_to'] ) ? $single_field['restriction_to'] : 'min';
    $restriction_type = ! empty( $single_field['restriction_type'] ) ? $single_field['restriction_type'] : 'word';

    $current_data = ! empty( $_POST[ $single_field['name'] ] ) ? sanitize_text_field( wp_unslash( $_POST[ $single_field['name'] ] ) ) : '';
    $label = ! empty( $single_field['label'] ) ? $single_field['label'] : '';

    // if restriction by character count
    if ( 'character' === $restriction_type && 'min' === $restriction_to ) {
        if ( strlen( $current_data ) < $restricted_num ) {
            $this->send_error( 'Minimum ' . $restricted_num . ' character required for ' . $label );
        }
    } elseif ( 'character' === $restriction_type && 'max' === $restriction_to ) {
        if ( strlen( $current_data ) > $restricted_num ) {
            $this->send_error( 'Maximum ' . $restricted_num . ' character allowed for ' . $label );
        }
    }

    // if restriction by word count
    if ( 'word' === $restriction_type && 'min' === $restriction_to ) {
        if ( str_word_count( $current_data ) < $restricted_num ) {
            $this->send_error( 'Minimum ' . $restricted_num . ' word required for ' . $label );
        }
    } elseif ( 'word' === $restriction_type && 'max' === $restriction_to ) {
        if ( str_word_count( $current_data ) > $restricted_num ) {
            $this->send_error( 'Maximum ' . $restricted_num . ' word allowed for ' . $label );
        }
    }
}
```

Feel free to notify us of any queries. You can close the issue if the problem is solved.

**Comment by ijdk-loop** [comment] 2022-01-11 06:51
i will try this and let you know, but please inform what happens if the plugin get updated?

**Comment by sapayth** [comment] 2022-01-11 10:15
Hello @ijdk-loop,
Don't worry, we are going to add the fix to the upcoming release.

**Comment by ijdk-loop** [comment] 2022-01-11 15:45
yes, it is working but would have great if the errors were more prominent, clear and pointing...

**Closed** 2022-03-01 08:31 UTC
