### ISSUE TITLE
WP User Frontend Pro - business, only plugin conflicting with GDPR Cookie Compliance Plugin

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#782] opened 2020-01-22 18:18 UTC
Out of 68 active plugins I have on my site, I found out that **WP User Frontend Pro - business** is the  only plugin conflicting with **GDPR Cookie Compliance Plugin**.

The only way I have to be able to edit the settings of **GDPR Cookie Compliance Plugin** is to turn OFF **WP User Frontend Pro - business**.

**Comment by itowhid06** [comment] 2020-01-30 11:24
Hello @Anticosti, I was unable to reproduce the issue with develop version from Github. If you are still facing the issue please feel free open a ticket [Here](https://wedevs.com/account/tickets/). I am closing the ticket for now. Thank you for your understanding.

**Closed by itowhid06** 2020-01-30 11:24 UTC
Labels: need-more-details
